spring:
  datasource:
    url: jdbc:mysql://localhost:3306/gym
    username: gymuser
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    open-in-view: true

logging:
  level:
    root: info
    org:
      springframework:
        boot:
          web: info


management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,custom
  endpoint:
    health:
      show-details: always
    metrics:
      enabled: true
    prometheus:
      enabled: true
  prometheus:
    metrics:
      export:
        enabled: true